#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config normal_border_color \#000000
bspc config focused_border_color \#5e4e6f
bspc config border_width         3
bspc config window_gap          0
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# auto start applications
~/Scripts/cursor.sh &
udiskie -a &
exec_always no-startup-id picom -b --config ~/.config/picom/picom.conf &

